name: Release

on:
  push:
    branches: [master]

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      api-released: ${{ steps.release.outputs['services/mr-review--release_created'] }}
      api-version: ${{ steps.release.outputs['services/mr-review--major'] }}.${{ steps.release.outputs['services/mr-review--minor'] }}.${{ steps.release.outputs['services/mr-review--patch'] }}
      web-released: ${{ steps.release.outputs['services/web-app--release_created'] }}
      web-version: ${{ steps.release.outputs['services/web-app--major'] }}.${{ steps.release.outputs['services/web-app--minor'] }}.${{ steps.release.outputs['services/web-app--patch'] }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

